#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /usr/bin/chromium 40
    update-alternatives --install /usr/bin/gnome-www-browser \
        gnome-www-browser /usr/bin/chromium 40
fi

cp /usr/lib/chromium/chrome-sandbox /usr/lib/chromium-browser/
chmod 4755 /usr/lib/chromium-browser/chrome-sandbox
